In [22]:
%load_ext autoreload
%autoreload 2
from particle import Particle
import numpy as np
import sys
sys.path.append("/hetghome/antonpr/xmax_sigma/flincpy")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [23]:
from data_structs.pdg_pid_map import PdgPidMap, PdgLists

In [24]:
pdg_list = PdgLists()

In [29]:
pdg_list.hadron_emix[[111, 130, 2212, 2112]]

array([1.12201845e+09, 2.23872114e+01, 0.00000000e+00, 1.12201845e-01])

In [8]:
hmix_map = PdgPidMap({pdg : pid for pid, pdg in enumerate(pdg_list.hadrons_mix_mceq)})

In [12]:
pdg_list.hadron_emix_map

{111: 1122018454.3019652,
 130: 22.38721138568341,
 -211: 7.079457843841384,
 211: 8.91250938133746,
 310: 8912.509381337459,
 -321: 70.79457843841384,
 321: 89.12509381337459,
 -411: 2238721.138568342,
 411: 2238721.138568342,
 -421: 4466835.921509635,
 421: 4466835.921509635,
 -431: 4466835.921509635,
 431: 4466835.921509635,
 -2112: 0.11220184543019636,
 2112: 0.11220184543019636,
 -3122: 5623.4132519034965,
 3122: 5623.4132519034965}

In [11]:
hmix_map.pdg_pid

array([  111,   130,  -211,   211,   310,  -321,   321,  -411,   411,
        -421,   421,  -431,   431, -2112,  2112, -3122,  3122],
      dtype=int32)

In [20]:
mix_en_table = np.zeros_like(hmix_map.pid_pdg, dtype=np.float64)

for pdg, emix in pdg_list.hadron_emix_map.items():
    mix_en_table[pdg] = emix
    

In [21]:
mix_en_table[[111, 130, 11]]

array([1.12201845e+09, 2.23872114e+01, 0.00000000e+00])

In [6]:
from propagation.interaction.csec_tables import CrossSectionTableMCEq
from propagation.interaction.csec_on_table import CrossSectionOnTable
from data_structs.pdg_pid_map import PdgPidMap, PdgLists

cs_table = CrossSectionTableMCEq()
# cs_table.add_pdgs(PdgLists().longer_pi0_to_mceq)

csec = CrossSectionOnTable(cs_table)



# pdg_list = np.array([111, 111, 111, 
#                     111, -211, 
#                     111, 111, 2212, 111], dtype=np.int32)
pdg_list = np.array([13, -13, 11, -11, 22, 111, -211], dtype=np.int32)
energy_list = np.array([5e3, 5e2, 4e6, 4e3, 2e5, 2e5, 4e3, 5e2, 2e5], dtype=np.float64)    

print(csec.get_mean_xdepth(pdg_list, energy_list))
print(csec.get_xdepth(pdg_list, energy_list))

MCEqRun::set_interaction_model(): DPMJETIII191
ParticleManager::_init_default_tracking(): Initializing default tracking categories (pi, K, mu)
MCEqRun::set_density_model(): Setting density profile to CORSIKA ('BK_USStd', None)
MCEqRun::set_primary_model(): Primary model set to Hillas-Gaisser (H3a)
Tabulate cross-section for pi0(111)
Tabulate cross-section for K_L0(130)
Tabulate cross-section for pi-(-211)
Tabulate cross-section for pi+(211)
Tabulate cross-section for K_S0(310)
Tabulate cross-section for K-(-321)
Tabulate cross-section for K+(321)
Tabulate cross-section for D-(-411)
Tabulate cross-section for D+(411)
Tabulate cross-section for Dbar0(-421)
Tabulate cross-section for D0(421)
Tabulate cross-section for D_s-(-431)
Tabulate cross-section for D_s+(431)
Tabulate cross-section for nbar0(-2112)
Tabulate cross-section for n0(2112)
Tabulate cross-section for pbar-(-2212)
Tabulate cross-section for p+(2212)
Tabulate cross-section for Lambdabar0(-3122)
Tabulate cross-section for Lam

In [10]:
csec.pmap.pid_pdg[20313]

IndexError: index 20313 is out of bounds for axis 0 with size 6245

In [20]:
csec.pmap.get_pids([22, 20313, 111, 2212, -431,   431])

array([-2147483640, -2147483640,           0,          16,          11,
                12], dtype=int32)

In [17]:
csec.pmap.known_pdg_ids

array([  111,   130,  -211,   211,   310,  -321,   321,  -411,   411,
        -421,   421,  -431,   431, -2112,  2112, -2212,  2212, -3122,
        3122])

In [5]:
all_particles_dict = {p.pdgid: p for p in Particle.findall()}
pmap = PdgPidMap({int(pdgid) : pid for pid, 
                               pdgid in enumerate(all_particles_dict)}
                             )

In [8]:
pmap.get_pdgs([11, 12, -12, 4321, 55])

array([         -6,          11,  1001132860, -1000671700,         310],
      dtype=int32)

In [12]:
pmap.get_pids([11, 12, -12, 4321, 55, 1001132860, -11])

array([         12,          14,          15, -2147483640, -2147483640,
              6484,          13], dtype=int32)

In [1]:
from MCEq.core import MCEqRun
import mceq_config as config
import crflux.models as pm
config.mceq_db_fname = "/hetghome/antonpr/MCEq/MCEq/data/mceq_db_lext_dpm191_v150.h5"

mceq_run = MCEqRun(
            #provide the string of the interaction model
            interaction_model="DPMJET-III-19.1",
            #primary cosmic ray flux model
            primary_model = (pm.HillasGaisser2012, "H3a"),
            # Zenith angle in degrees. 0=vertical, 90=horizontal
            theta_deg=0,
            density_model = ("CORSIKA", ("USStd", None))
        )

MCEqRun::set_interaction_model(): DPMJETIII191
ParticleManager::_init_default_tracking(): Initializing default tracking categories (pi, K, mu)
MCEqRun::set_density_model(): Setting density profile to CORSIKA ('USStd', None)
MCEqRun::set_primary_model(): Primary model set to Hillas-Gaisser (H3a)


In [3]:
%load_ext autoreload
%autoreload 2
from particle import Particle
import numpy as np
import sys
sys.path.append("/hetghome/antonpr/xmax_sigma/flincpy")

In [14]:
from data_structs.pdg_pid_map import PdgPidMap2, pdg2mceq_idx_map
import numpy as np

pdg2idx_mapper = PdgPidMap2(pdg2mceq_idx_map(mceq_run))

In [15]:
pdg2idx_mapper.known_pdg_ids

array([  -11,    11,   -12,    12,   -13,    13,   -14,    14,   -16,
          16,    22,   111,   130,  -211,   211,   310,  -321,   321,
        -411,   411,  -421,   421,  -431,   431, -2112,  2112, -2212,
        2212, -3122,  3122])

In [16]:
pdg2idx_mapper.known_pid_ids

array([ 1,  4,  6,  7,  9, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

In [13]:
pdg2idx_mapper.get_pids([-11, -2147483640, -2147483640,          11, -2147483640,
               -12])

array([          1, -2147483640, -2147483640,           4, -2147483640,
                 6], dtype=int32)

In [ ]:
def tabulate_ctau(self):
    self._ctau_tab = np.zeros(len(self.pmap.pdg_pid), dtype=np.float64)
    for pid, pdg in enumerate(self.pmap.pdg_pid):
        self._ctau_tab[pid] = self.get_ctau(pdg)
        
def tabulate_mass(self):
    self._mass_tab = np.zeros(len(self.pmap.pdg_pid), dtype=np.float64)
    for pid, pdg in enumerate(self.pmap.pdg_pid):
        self._mass_tab[pid] = self.get_mass(pdg) 

In [31]:
pdg_list = PdgLists()

In [32]:
(len(pdg_list.hadrons_mix_mceq) + len(pdg_list.hadrons_stable_mceq) +
 len(pdg_list.leptons_decay_mceq) + len(pdg_list.leptons_stable_mceq)) 

30

In [30]:
a = np.array([1, 2, 3, 4, 5])

a[a == 5]

array([5])

In [1]:
import numpy as np

a = np.array([-1, 2, -1, -5, 3, -3, 5, -2])
np.unique(a)

array([-5, -3, -2, -1,  2,  3,  5])

In [4]:
aa = []
aa += [9, 8]
aa += [4, 5]
aa += [5, 2]

np.unique(aa)

array([2, 4, 5, 8, 9])