In [1]:
from particle_xdepths import default_xdepth_getter

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from decay_inter import DecayInteraction
from particle_array import ParticleArray, FilterCode
import numpy as np
pstack = ParticleArray(10)
    
pstack.push(pid = [3312, 5232, 3312, 5232], energy = [1e3, 1e3, 1e2, 6e2], 
            xdepth = [1e1, 1e1, 1e1, 1e1])
pstack.valid().filter_code[:] = FilterCode.XD_DECAY_OFF.value
pstack.valid().generation_num[:] = np.int32(0)

In [4]:

from decay_inter import DecayInteraction
dint = DecayInteraction()


In [5]:
dint(pstack)
print("pid = ", dint.get_finals().valid().pid)
print("energy = ", dint.get_finals().valid().energy)
print("xdepth_decay = ", dint.get_finals().valid().xdepth_decay)
print("xdepth = ", dint.get_finals().valid().xdepth)
print("gen_num = ", dint.get_finals().valid().generation_num)
print(len(dint.get_finals()))

pid =  [ 2112   111   -14   111 -2212   111  2112  2112   111   -14    22   111
   -14   111   111   -12    11    14    14   111  2212   -14    14   -14
    14   -12    11    14  2112   111    14   -14    14   -14   -12    11
    14    14    12   -11   -14    14   -14   -14   -12    11    14    12
   -11   -14   -12    11    14    12   -11   -14    12   -11   -14   -12
    11    14    12   -11   -14   -12    11    14    12   -11   -14    12
   -11   -14   -12    11    14   -12    11    14    14   -14    12   -11
   -14   -12    11    14]
energy =  [8.14203538e+02 7.77360832e+01 3.83310845e+01 1.89556098e+01
 1.49088871e+02 1.85755542e+01 3.00584979e+02 7.48096315e+01
 5.54455966e+00 7.95118870e+00 9.73562147e+00 1.48109622e+01
 3.72405992e+01 2.77827563e+01 2.75457264e+01 2.53723133e+01
 4.58556949e+00 3.97714114e+01 3.52925781e+00 4.52118375e+01
 1.18796030e+02 7.82317863e+00 8.16206698e+00 1.47593829e+01
 7.98978401e+00 4.66050059e+00 4.94645767e+00 2.08766182e+00
 1.08043484e+02 2.9

In [6]:
pstack.valid().filter_code[:] = FilterCode.XD_DECAY_OFF.value
# pstack.valid().filter_code[1:3] = 21
# print(pstack.valid().xdepth_decay)
print(pstack.valid().filter_code)
dint.calc_xdepth(pstack)
print(pstack.valid().xdepth)
print(pstack.valid().xdepth_decay)
print(pstack.valid().filter_code)


[22 22 22 22]
[10. 10. 10. 10.]
[10.03544772 10.00003911 10.00672008 10.00001378]
[21 21 21 21]
